import { useState } from 'react'
import { Sparkles, ClipboardCopy, Check, Wand2 } from 'lucide-react'
import { addHabit, CUSTOM_POINT_BUDGET } from '../lib/rooms.js'
import { parseHabitsImport, IMPORT_PROMPT } from '../lib/importHabits.js'
import { iconComponent } from '../icons.js'

// Paste habits generated by Claude and create them all at once.
export default function ImportHabits({ player, onChanged }) {
  const [text, setText] = useState('')
  const [copied, setCopied] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const { habits, errors } = text.trim() ? parseHabitsImport(text) : { habits: [], errors: [] }

  const customUsed = player.habits.filter((h) => !h.is_mandatory).reduce((s, h) => s + h.points, 0)
  const remaining = Math.max(0, CUSTOM_POINT_BUDGET - customUsed)
  const importTotal = habits.reduce((s, h) => s + (h.points || 0), 0)

  function copyPrompt() {
    navigator.clipboard?.writeText(IMPORT_PROMPT).then(() => {
      setCopied(true); setTimeout(() => setCopied(false), 1800)
    })
  }

  async function addAll() {
    if (!habits.length) return
    if (importTotal > remaining) {
      setError(`These habits total ${importTotal} pts but you only have ${remaining} left in your custom budget.`)
      return
    }
    setError('')
    setBusy(true)
    try {
      for (const h of habits) await addHabit(player.id, h)
      setText('')
      onChanged()
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="import">
      <div className="import-head">
        <Sparkles size={16} className="i-amber" />
        <b>Auto-import with Claude</b>
      </div>
      <p className="muted small">
        1. Copy the prompt into Claude and answer its questions. 2. Paste Claude's
        JSON below. 3. Add all your habits in one click.
      </p>

      <button className="chip" onClick={copyPrompt}>
        {copied ? <><Check size={14} /> Copied prompt</> : <><ClipboardCopy size={14} /> Copy the Claude prompt</>}
      </button>

      <textarea
        className="import-box"
        placeholder='Paste Claude&apos;s JSON here (the whole ```json block)…'
        value={text}
        onChange={(e) => setText(e.target.value)}
        rows={4}
      />

      {errors.length > 0 && <p className="errline">{errors[0]}</p>}

      {habits.length > 0 && (
        <>
          <div className="import-preview">
            {habits.map((h, i) => {
              const Icon = iconComponent(h.icon)
              return (
                <span key={i} className="import-chip" style={{ '--habit': h.color }}>
                  <Icon size={13} /> {h.label}
                </span>
              )
            })}
          </div>
          <button onClick={addAll} disabled={busy}>
            <Wand2 size={15} /> {busy ? 'Adding…' : `Add ${habits.length} habit${habits.length > 1 ? 's' : ''}`}
          </button>
          {error && <p className="errline">{error}</p>}
        </>
      )}
    </div>
  )
}
